name: SonarQube Scan
on: [push]

jobs:
  sonar-scan:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Sonar Scanner
      run: |
        sonar-scanner
